### PR TITLE
Fix the Birecursive type class.

### LINKED ISSUE #44: Add `Birecursive` type class
The direct approach of
```scala
sealed trait Birecursive[T] extends Recursive[T] with Corecursive[T]
```
doesn’t seem to cut it when an abstract type member is in play, so we need something more clever.

I, @paulp, and @edmundnoble have taken swipes at this so far.

### PR DESCRIPTION
**Pull request by sellout**
Fixes #44.

Replaces all instances and constraints that were both `Recursive` and
`Corecursive` with `Birecursive`. Move type class operations with both
constraints to the `Birecursive` type class (including overloading some
operations that have better implementations with both constraints).

Also added `gcataZygo`, which enables an overload of `paraZygo` in
`Birecursive`. And added `Delay.apply`.

### CODE REVIEW

File: core/shared/src/main/scala/matryoshka/Birecursive.scala [hunk 1]
```diff
@@ -16,18 +16,160 @@
...
-  *     #44 is resolved. Define an instance of [[BirecursiveT]] if possible,
-  *     otherwise define separate [[Recursive]] and [[Corecursive]] instances.
   */
-// TODO: Once this type class is actually usable, operations in `Recursive` and
-//       `Corecursive` that also have a `Corecursive.Base[T, Base]` constraint
-//       should be moved here.
-trait Birecursive[T] extends Recursive[T] with Corecursive[T]
+trait Birecursive[T] extends Recursive[T] with Corecursive[T] { self =>
+  implicit val rec: Recursive.Aux[T, Base] = self
+  implicit val corec: Corecursive.Aux[T, Base] = self
```
Comment (sellout) [inline core/shared/src/main/scala/matryoshka/Birecursive.scala]: These implicits allow the constraints used in definition here to be satisfied.

File: core/shared/src/main/scala/matryoshka/implicits/package.scala [hunk 2]
```diff
@@ -23,15 +23,28 @@ package object implicits
     with Merge.ToMergeOps
     with Recursive.ToRecursiveOps {
 
+  implicit def toRecursive[T, F[_]](implicit T: Birecursive.Aux[T, F])
+      : Recursive.Aux[T, F] =
+    T.rec
+
+  implicit def toCorecursive[T, F[_]](implicit T: Birecursive.Aux[T, F])
+      : Corecursive.Aux[T, F] =
+    T.corec
```
Comment (sellout) [inline core/shared/src/main/scala/matryoshka/implicits/package.scala]: And these implicits expose the ones defined in the type class, so now everything can resolve Rec/Corec operations given a Birec constraint.

**Comment by sellout** [comment]
In addition to the people I added as reviewers, I figure @edmundnoble and @milessabin may also have thoughts about the way I managed to get `<super>.Aux` to resolve from `<sub>.Aux`.

File: core/shared/src/main/scala/matryoshka/Birecursive.scala (hunk 1 above)
Comment (milessabin) [inline core/shared/src/main/scala/matryoshka/Birecursive.scala]: Given the later `toRecursive` and `toCorecursive` definitions, do these two actually need to be implicit?

File: core/shared/src/main/scala/matryoshka/Recursive.scala [hunk 3]
```diff
@@ -165,6 +165,16 @@ trait Recursive[T] extends Based[T] {
       A =
     gcata[Cofree[H, ?], A](t)(distGHisto(g), f)
 
+  def gcataZygo[W[_]: Comonad, A, B]
```
Comment (drostron) [inline core/shared/src/main/scala/matryoshka/Recursive.scala]: Is there a corresponding test?

File: core/shared/src/main/scala/matryoshka/package.scala [hunk 4]
```diff
@@ -177,34 +176,32 @@ package object matryoshka {
   }
 
   // TODO: Move this to `Birecursive` once that works.
-  def birecursiveIso[T, F[_]: Functor]
-    (implicit TR: Recursive.Aux[T, F], TC: Corecursive.Aux[T, F]) =
+  def birecursiveIso[T, F[_]: Functor](implicit T: Birecursive.Aux[T, F]) =
```
Comment (sellout) [inline core/shared/src/main/scala/matryoshka/package.scala]: Umm, nothing, I think 😄 I should do that.

File: core/shared/src/main/scala/matryoshka/Recursive.scala (hunk 3 above)
Comment (sellout) [inline core/shared/src/main/scala/matryoshka/Recursive.scala]: Indirectly, because of https://github.com/slamdata/matryoshka/pull/79/files/2641f7f624f4e15d3df1974b4532f874aac94021#diff-08bebdfb63dd73c8d3dab8adcf5d9777R73
